'use strict';
const {dateKey,monthDays,durationMinutes,formatDuration,formatTime,monthLabel,weekday,makeWorkRecord,makeOffRecord,pad}=WorkRecords;
let recordsMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),summaryMonth=new Date(recordsMonth),editingKey=null,editingOriginalKey=null,editingOff=false;
const $=id=>document.getElementById(id);
async function allMap(){const rows=await WorkDB.allDays();return Object.fromEntries(rows.map(r=>[r.date,r]));}
async function selectedShop(){return (await WorkDB.getMeta('lastShop'))||''}
async function renderHome(){const m=await allMap(),now=new Date(),k=dateKey(now),r=m[k]||{},shop=r.shop||await selectedShop();$('homeDate').textContent=now.toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long'}).replace(/^./,c=>c.toUpperCase());$('homeStart').textContent=formatTime(r.start);$('homeEnd').textContent=formatTime(r.end);$('homeDuration').textContent=r.end?formatDuration(durationMinutes(r)):r.start?formatDuration(Math.max(0,Math.round((Date.now()-r.start)/60000)-(Number(r.breakMin)||0))):'0:00';$('homeState').textContent=r.off?'OFF':r.start&&!r.end?'Çalışıyor':r.end?'Tamamlandı':'Hazır';$('homeBanner').textContent=r.off?'Bugün OFF olarak işaretlendi.':r.start&&!r.end?'Çalışma devam ediyor.':r.end?'Bugünkü kayıt tamamlandı.':'Henüz bugün giriş yapılmadı.';document.querySelectorAll('.shop-choice').forEach(b=>b.classList.toggle('selected',b.dataset.shop===shop));$('startWork').disabled=!!(r.start&&!r.end)||!!r.off||!!r.end;$('stopWork').disabled=!r.start||!!r.end||!!r.off;}
async function renderRecords(){const m=await allMap();$('recordsMonth').textContent=monthLabel(recordsMonth);const frag=document.createDocumentFragment();for(const k of monthDays(recordsMonth)){const r=m[k],d=new Date(`${k}T12:00:00`),box=document.createElement('article');box.className='record-card';box.dataset.date=k;if(!r||r.archived){box.classList.add('empty-record');box.innerHTML=`<div class="date-block"><strong>${d.getDate()}</strong><small>${weekday(k)}</small></div><div class="record-main"><b>${r?.archived?'Arşivlendi':'OFF / kayıt yok'}</b></div>`}else if(r.off){box.classList.add('off-record');box.innerHTML=`<div class="date-block"><strong>${d.getDate()}</strong><small>${weekday(k)}</small></div><div class="record-main"><b>OFF</b>${r.note?`<small>${UI.esc(r.note)}</small>`:''}</div><button class="edit-record" data-edit="${k}">Düzenle</button>`}else{box.innerHTML=`<div class="date-block"><strong>${d.getDate()}</strong><small>${weekday(k)}</small></div><div class="record-main"><b>${formatTime(r.start)} → ${formatTime(r.end)}</b><small>${r.breakMin?'Mola '+r.breakMin+' dk':'Mola yok'}</small><strong class="shop-line">${UI.esc(r.shop||'Dükkan seçilmedi')}</strong>${r.note?`<small>📝 ${UI.esc(r.note)}</small>`:''}</div><div class="record-right"><strong>${r.end?formatDuration(durationMinutes(r)):'…'}</strong><button class="edit-record" data-edit="${k}">Düzenle</button></div>`}frag.appendChild(box)}$('recordList').replaceChildren(frag);$('recordList').querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>openEdit(b.dataset.edit)));}
async function renderSummary(){const m=await allMap(),target=(Number(await WorkDB.getMeta('target'))||8)*60,rate=Number(await WorkDB.getMeta('rate'))||0;let total=0,days=0,ot=0;for(const k of monthDays(summaryMonth)){const r=m[k];if(r&&!r.off&&!r.archived&&r.start&&r.end){const z=durationMinutes(r);total+=z;days++;ot+=Math.max(0,z-target)}}$('summaryMonth').textContent=monthLabel(summaryMonth);$('summaryTotal').textContent=formatDuration(total);$('summaryDays').textContent=days;$('summaryAvg').textContent=days?formatDuration(Math.round(total/days)):'0:00';$('summaryOT').textContent=formatDuration(ot);const bonus=Number(await WorkDB.getMeta('bonus'))||0;$('summaryPay').textContent=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(total/60*rate+bonus);}
function openModal(k=null){editingKey=k;editingOriginalKey=k;const modal=$('editModal');WorkDB.getDay(k).then(r=>{editingOff=!!r?.off;$('modalTitle').textContent=k?'Gün düzenle':'Yeni gün';$('editDate').value=k||dateKey(new Date());$('editStart').value=r?.start?new Date(r.start).toTimeString().slice(0,5):'';$('editEnd').value=r?.end?new Date(r.end).toTimeString().slice(0,5):'';$('editBreak').value=r?.breakMin??0;$('editShop').value=r?.shop||'';$('editNote').value=r?.note||'';setEditType(editingOff);modal.classList.add('open')})}
function setEditType(off){editingOff=off;$('workType').classList.toggle('active',!off);$('offType').classList.toggle('active',off);$('workFields').hidden=off;}
function closeModal(){$('editModal').classList.remove('open');editingKey=null;editingOriginalKey=null;}
async function saveEdit(){const k=$('editDate').value;if(!k)return UI.showToast('Tarih seçmelisin','error');const old=editingOriginalKey?await WorkDB.getDay(editingOriginalKey):await WorkDB.getDay(k);let r;if(editingOff)r=makeOffRecord(k,$('editNote').value);else{if(!$('editStart').value||!$('editEnd').value)return UI.showToast('Başlangıç ve bitiş saatini gir','error');if(!$('editShop').value)return UI.showToast('Dükkan seçmelisin','error');r=makeWorkRecord({date:k,start:$('editStart').value,end:$('editEnd').value,breakMin:$('editBreak').value,note:$('editNote').value,shop:$('editShop').value});r={...old,...r};}await WorkDB.putDay(r);if(editingOriginalKey&&editingOriginalKey!==k)await WorkDB.deleteDay(editingOriginalKey);closeModal();await renderRecords();await renderSummary();await renderHome();UI.showToast('Kayıt güncellendi');}
async function archiveEdit(){if(!editingOriginalKey)return UI.showToast('Yeni kaydı arşivleyemezsin','error');const r=await WorkDB.getDay(editingOriginalKey);if(r){r.archived=true;await WorkDB.putDay(r);}closeModal();await renderRecords();await renderSummary();UI.showToast('Kayıt arşivlendi');}
async function startWork(){const shop=await selectedShop();if(!shop)return UI.showToast('Önce dükkan seç','error');const k=dateKey(new Date()),old=await WorkDB.getDay(k);if(old?.end)return UI.showToast('Bugünkü kayıt zaten tamamlandı','error');if(old?.start&&!old.end)return UI.showToast('Bugün zaten çalışıyorsun','error');const r={...old,date:k,start:Date.now(),end:null,breakMin:old?.breakMin??(Number(await WorkDB.getMeta('defaultBreak'))||0),note:old?.note||'',shop,off:false,archived:false,updatedAt:Date.now()};await WorkDB.putDay(r);await renderHome();UI.showToast('İşe başladın');}
async function stopWork(){const k=dateKey(new Date());let r=await WorkDB.getDay(k);if(!r?.start||r.end||r.off){const open=(await WorkDB.allDays()).filter(x=>x.start&&!x.end&&!x.off&&!x.archived).sort((a,b)=>b.start-a.start)[0];if(open)r=open;}if(!r?.start)return UI.showToast('Önce işe başla','error');r.end=Date.now();r.updatedAt=Date.now();await WorkDB.putDay(r);await renderHome();await renderRecords();await renderSummary();UI.showToast('İş tamamlandı');}
async function generateCurrentPDF(){const rows=(await WorkDB.allDays()).filter(r=>r.date.startsWith(`${recordsMonth.getFullYear()}-${pad(recordsMonth.getMonth()+1)}-`)&&!r.off&&!r.archived&&r.start&&r.end).sort((a,b)=>a.date.localeCompare(b.date));const total=rows.reduce((s,r)=>s+durationMinutes(r),0);WorkReports.downloadPDF(recordsMonth,rows,total);}
async function saveSettings(){await WorkSettings.saveGeneralSettings();await renderSummary();}
async function refresh(){await renderHome();await renderRecords();await renderSummary();}
function bind(){
  document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',async()=>{UI.setActiveTab(b.dataset.tab);if(b.dataset.tab==='home')await renderHome();if(b.dataset.tab==='records')await renderRecords();if(b.dataset.tab==='summary')await renderSummary();if(b.dataset.tab==='settings')await WorkSettings.renderSettings();}));
  document.querySelectorAll('.shop-choice').forEach(b=>b.addEventListener('click',async()=>{await WorkDB.setMeta('lastShop',b.dataset.shop);await renderHome();}));
  $('startWork').addEventListener('click',startWork);$('stopWork').addEventListener('click',stopWork);$('addDay').addEventListener('click',()=>openModal());$('editCancel').addEventListener('click',closeModal);$('editSave').addEventListener('click',saveEdit);$('editArchive').addEventListener('click',archiveEdit);$('workType').addEventListener('click',()=>setEditType(false));$('offType').addEventListener('click',()=>setEditType(true));$('editModal').addEventListener('click',e=>{if(e.target.id==='editModal')closeModal()});
  $('recordsPrev').addEventListener('click',async()=>{recordsMonth=new Date(recordsMonth.getFullYear(),recordsMonth.getMonth()-1,1);await renderRecords()});$('recordsNext').addEventListener('click',async()=>{recordsMonth=new Date(recordsMonth.getFullYear(),recordsMonth.getMonth()+1,1);await renderRecords()});$('summaryPrev').addEventListener('click',async()=>{summaryMonth=new Date(summaryMonth.getFullYear(),summaryMonth.getMonth()-1,1);await renderSummary()});$('summaryNext').addEventListener('click',async()=>{summaryMonth=new Date(summaryMonth.getFullYear(),summaryMonth.getMonth()+1,1);await renderSummary()});$('pdfDownload').addEventListener('click',generateCurrentPDF);$('settingsSave').addEventListener('click',saveSettings);
  document.querySelectorAll('[data-settings-page]').forEach(b=>b.addEventListener('click',()=>WorkSettings.openPage(b.dataset.settingsPage))); $('settingsDetailClose').addEventListener('click',()=>WorkSettings.closePage()); $('settingsDetail').addEventListener('click',e=>{if(e.target.id==='settingsDetail')WorkSettings.closePage();});
}
window.refreshApp=refresh; (async()=>{try{bind();await WorkSettings.renderSettings();await refresh();}catch(e){console.error(e);UI.showToast('Uygulama başlatılamadı','error')}})();
setInterval(()=>{if(document.getElementById('screen-home').classList.contains('active'))renderHome().catch(console.error)},30000);
if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(console.error);
